spring:
  #jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true

  #database
  datasource:
    #for using class path schema.sql and data.sql
#    initialization-mode: ALWAYS
      #h2
    url: jdbc:h2:mem:springit
    #MySql
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springit
#    username: root
#    password: root

